### ISSUE TITLE
Issue installing from gnu elpa due to bad signature.

### ISSUE THREAD

**Issue by dantheobserver** [Malabarba/spinner.el#14]
I'm trying to install a package that depends on spinner but get the following when trying to install both the depending package or this package alone

```Failed to verify signature spinner-1.7.3.el.sig:
Bad signature from 474F05837FBDEF9B GNU ELPA Signing Agent <elpasign@elpa.gnu.org>
Command output:
gpg: Signature made Thu 17 Nov 2016 02:05:02 PM PST
gpg:                using DSA key 474F05837FBDEF9B
gpg: BAD signature from "GNU ELPA Signing Agent <elpasign@elpa.gnu.org>" [unknown]
```

I am using emacs 25.  One thing is that I am in an isolated environment by changing `HOME` when running emacs to another directory with a particular .emacs.d as I have another folder by that name in my home folder.

**Comment by Malabarba** [comment]
Hi there. Sorry for the long radio silence

If you're still getting this issue it needs to be reported to GNU Emacs itself (though you might find some help by googling around). Packages delivered via GNU Elpa are signed by GNU Elpa, not by the package maintainer.
