### ISSUE TITLE
Can this be added to the compilation buffer?

### ISSUE THREAD

**Issue by minad** [Malabarba/spinner.el#16]
Is it possible to modify the mode line of the compilation buffer? Is there a generic mechanism, which is used to extend the mode line?

https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/compile.el

**Comment by Malabarba** [comment]
Hi @minad 
There's no config option for that. But simply calling the correct functions in compilation-mode hooks should be enough. Give this a try:

(add-hook 'compilation-start-hook #'spinner-start)
(add-hook 'compilation-finish-functions (lambda (&rest _) (spinner-stop)))

**Comment by minad** [comment]
Thank you, that works!
