### ISSUE TITLE
wrong-type-argument timerp

### ISSUE THREAD

**Issue by manuel-uberti** [Malabarba/spinner.el#25]
Hi,

on a recent Emacs 28 (commit: `03dcceeeeeda6cefe4c0a79be328dd44b289b20b`), I did this:

- emacs -Q
- M-x package-initialize
- M-x toggle-debug-on-error
- (spinner-start)

And then I got

```
Debugger entered--Lisp error: (wrong-type-argument timerp [t nil nil nil nil nil nil nil nil])
  timer--time-setter([t nil nil nil nil nil nil nil nil] (24878 14508 400000 0))
  timer-set-time([t nil nil nil nil nil nil nil nil] (24878 14508 400000 0) 0.1)
  spinner--start-timer(#s(spinner :frames ["┤" "┘" "┴" "└" "├" "┌" "┬" "┐"] :counter 0 :fps 10 :timer [t nil nil nil nil nil nil nil nil] :active-p t :buffer #<buffer *scratch*> :delay 0))
  spinner-start()
  (progn (spinner-start))
  eval((progn (spinner-start)) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by Malabarba** [comment]
Looks like something changed in the byte-compilation output between 27 and 28 in a way that's not backwards compatible.
I managed to reproduce the same problem here, and it got fixed by just reinstalling the package. (or you can recompile, if you know how to that)

**Comment by manuel-uberti** [comment]
Thank you for the quick reply. You're right: reinstalling the package fixed the problem.

**Comment by Malabarba** [comment]
No problem Manuel.
If you feel like it, this might be worth submitting a bug report.
