### ISSUE TITLE
`package-initialize` gives "Error: (void-function defstruct) [2 times]"

### ISSUE THREAD

**Issue by cute-jumper** [Malabarba/spinner.el#3]
After searching all the autoload files I have, I found spinner.el has an autoload containing `defstruct`. Any way to eliminate the error?

**Comment by dahanbn** [comment]
Immediately after updating all my packages the debugger produced also the above mentioned error message.

```
 Debugger entered--Lisp error: (void-function defstruct)
      (defstruct (spinner (:copier nil) (:conc-name spinner--) (:constructor make-spinner (&optional type buffer-local fps) "Create a spinner of the given TYPE.       AND SO ON
```

I don't use spinner directly but I guess it's a dependency of paradox.
