### ISSUE TITLE
Publish on MELPA

### ISSUE THREAD

**Issue by cartolari** [Malabarba/spinner.el#5]
Would be great if this package could be installed from MELPA.

**Comment by andyleejordan** [comment]
FYI it's already published on [ELPA](https://elpa.gnu.org/packages/spinner.html).

**Comment by cartolari** [comment]
So accustomed to just use MELPA that I didn't even notice it was already on ELPA,
Thanks for the info.

**Comment by andyleejordan** [comment]
RMS would be so ashamed :neckbeard:
